
services:
  db:
    image: postgres:16
    container_name: pokemon_db
    environment:
      POSTGRES_DB: tokka_intern_assignment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tokka_intern_assignment"]
      interval: 5s
      timeout: 5s
      retries: 10
  app:
    build: ./app
    container_name: pokemon_service
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
